### ISSUE TITLE
Question about annotation

### ISSUE THREAD

**Issue by dantin** [gugemichael/nesty#1]
Hi, I'm interested with this project, and I have a small question.

Since you'll integrate with Spring, why doesn't you use the annotation on spring-context/spring-web directly? As there are @Controller already...

**Comment by dantin** [comment]
One more thing, in the constructor of ControllerMethodDescriptor.java

try {
    // FIXME integrate with spring framework
    this.target = clazz.getClazz().newInstance();
} catch (InstantiationException | IllegalAccessException ignored) {
    ignored.printStackTrace();
}

this will bring wiring issue when integrate with spring framework

**Comment by gugemichael** [comment]
@dantin glad to receive your issue. the first question about reuse spring-context/spring-web annotation. My idea is to keep Nesty seperated with Spring. keep it lightly and clean. But if someone (like your propose) is highly recommended that they can integrate or migrate previous code without change any lines. I think it may be developed out in future(may be next version). and I hope and appreciate you can work on it.

**Comment by gugemichael** [comment]
@dantin about the second question. I consider it related the first. class.newInstance() called on every http request has be changed to call newInstance() just once on Nesty initial stage. this instance will be kept in whole NestServer lifecycle (in order to optimize).

**Comment by dantin** [comment]
Thanks for your time.
