### ISSUE TITLE
nesty组件中的GenericFileWriter有改进的地方

### ISSUE THREAD

**Issue by adol001** [gugemichael/nesty#2]
在多线程环境中，当程序结束时，必须在每个线程中都要进行flush，然后再在某个线程中进行close，才能确保没有数据没被漏掉

这是因为close的时候只会对本线程的thread local buffer进行flush，但是其他线程的thread local buffer中的数据就被漏掉了

可以考虑这样

    public static Map<String, ByteArrayBuffer> MAP = new HashMap<>();
    /**
     * thread cached calender instances
     */
    private ThreadLocal<ByteArrayBuffer> arena = new ThreadLocal<ByteArrayBuffer>() {
        @Override
        protected ByteArrayBuffer initialValue() {
            // Java fill the array buffer with zero
            ByteArrayBuffer result = new ByteArrayBuffer();
            MAP.put(Thread.currentThread().getName(), result);
            return result;
        }
    };

    @Override
    public void close() {
        try {
            if (buffered) {
                for(String key : MAP.keySet()){
                    ByteArrayBuffer buffer = MAP.get(key);
                    if (buffer.getOffset() != 0)
                        doWrite(buffer.getBuffer(), 0, buffer.getOffset());
                        buffer.clear();
                }
            }
            out.flush();
        } catch (IOException e) {
            e.printStackTrace();
        }

        try {
            out.close();
            out = null;
        } catch (IOException ignored) {
        }
    }

**Comment by gugemichael** [comment]
Thanks @adol001 ! 借鉴了你的思路，GenericFileWriter的ThreadLocal我直接换成ConcurrentHashMap(key直接是thread_id)来替换，并且在doWrite和close时候通过refcount来避免最后刷盘的线程冲突，保证close()时候如果还有doWrite在执行，就把清理过程交由用户线程去处理(最后refcount == 0的线程)。具体可见branch v0.0.3 758e3f123e56106908c8a0384a9f32df6c6f595a

多谢issue反馈!!

**Comment by waterflowhan** [comment]
准备上手了，感谢
